### ISSUE TITLE
Reorder parameter

### ISSUE THREAD

**Issue by witooh** [onedaycat/ts-error#9]
https://github.com/onedaycat/ts-error/blob/7e092c4bbb73d3d486246cdd5c8d766fd0306009/src/AppError.ts#L11

Reorder parameter in constructor to
`constructor(code: string, message: string, input?: any, cause?: object) `

**Comment by prapansak** [comment]
@witooh , why to reorder parameter to `(..., input?: any, cause?: object)` instead of `(...,  cause?: object, input?: any)`
